apiVersion: 1

datasources:
  - name: InfluxDB_v2_IIoT
    type: influxdb
    uid: influx_iiot
    access: proxy
    isDefault: true
    url: ${INFLUX_URL}
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
